---
name: build

on:
  push:
  schedule:
  # Weekly build at 20:55 on Sundays
  - cron: '55 20 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          tags: ${{ github.repository_owner }}/keycloak:latest
